config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  resource :users
  resources :games do
    resources :moves, only: [:create]
  end
  root 'games#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  has_many :user_games
  has_many :users, through: :user_games
  has_many :moves

  STATUSES ||= {
    new_game: 1,
    started: 2,
    with_draw: 3,
    finished: 4
  }.freeze

  MOVES ||= {
    cross: 1,
    nought: 2
  }.freeze

  GAME_STATUS = ['status'].freeze

  enum status: STATUSES

  scope :successful_games, -> { where.not(status: %w[new_game started]) }
  scope :new_games, -> { where(status: 'new_game') }

  accepts_nested_attributes_for :moves

  WINNING_COMBINATIONS = [
    [1, 2, 3], [4, 5, 6], [7, 8, 9],
    [1, 4, 7], [2, 5, 8], [3, 6, 9],
    [1, 5, 9], [3, 5, 7]
  ].freeze

  def check_winner
    board_moves = moves.filled
    player1 = board_moves.cross.pluck(:position).sort
    player2 = board_moves.nought.pluck(:position).sort

    if WINNING_COMBINATIONS.include?(player1)
      user = user_games.cross.user
      return [user, true]
    end

    if WINNING_COMBINATIONS.include?(player2)
      user = user_games.nought.user
      return [user, true]
    end
    [nil, false]
  end

  def finish!(winner_id = nil)
    finilised_result(winner_id)
    finished!
  end

  def game_board
    moves.map do |move|
      {
        id: move.id,
        position: move.position,
        game_id: move.game_id,
        box: move.box
      }
    end.as_json
  end

  def new_game
    [*1..9].each do |i|
      moves.new(position: i)
    end
    save! && self
  end

  def withdraw!
    ActiveRecord::Base.transaction do
      with_draw! if new_game? || started?
    end
    user_games.update_all(result: UserGame::RESULTS[:tie])
    ActionCable.server.broadcast("game_channel_#{id}",
                                 { action: 'with_draw',
                                   result: attributes.slice(*GAME_STATUS) })
  end

  private

  def finilised_result(winner_id = nil)
    ActiveRecord::Base.transaction do
      if winner_id.present?
        user_games.find_by(user_id: winner_id, game_id: id).update_attributes(result: UserGame::RESULTS[:win])
        user_games.where(game_id: id).where.not(user_id: winner_id).update_all(result: UserGame::RESULTS[:lost])
      else
        user_games.update_all(result: UserGame::RESULTS[:tie])
      end
    end
  end
end

app/models/move.rb
# frozen_string_literal: true

class Move < ApplicationRecord
  belongs_to :game
  validates :position, presence: true,
                       numericality: { only_integer: true, less_than: 10,
                                       greater_than: 0, message: 'Position limit exceeded' }

  scope :filled, -> { where(box: [1, 2]) }
  scope :cross, -> { where(box: 1) }
  scope :nought, -> { where(box: 2) }
  after_update_commit :check_game_winner

  def check_game_winner
    winner = false
    tie = false
    user, winner = game.check_winner if game.moves.filled.count >= 4
    tie = (game.moves.filled.count >= 9)
    if winner || tie
      ActionCable.server.broadcast("game_channel_#{game.id}",
                                   { action: 'result', winner: winner, tie: tie, user: { id: user&.id, name: user&.name },
                                     game_id: game.id, path: '/users/new' })
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :user_games
  has_many :games, through: :user_games

  validates :name, length: 3..50
end

app/models/user_game.rb
# frozen_string_literal: true

class UserGame < ApplicationRecord
  belongs_to :game
  belongs_to :user

  before_create :assign_the_game_symbol

  RESULTS ||= {
    win: 1,
    lost: 2,
    tie: 3,
    starting: 4
  }.freeze

  MOVES ||= {
    cross: 1,
    nought: 2
  }.freeze

  enum result: RESULTS
  enum symbol: MOVES

  scope :starting_games, -> { where(result: 'starting') }
  scope :cross, -> { find_by(symbol: MOVES[:cross]) }
  scope :nought, -> { find_by(symbol: MOVES[:nought]) }

  def assign_the_game_symbol
    self.symbol = if game.user_games.count.zero?
                    MOVES[:cross]
                  else
                    MOVES[:nought]
                  end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :get_user, only: %i[new create update]

  # Renders game board for new joined user
  # @controller_action_param :user [User]
  def new
    @game = GameService.connect(@user)
    if @game.blank?
      @game = Game.new
      @game.users << @user
      @game = @game.new_game
    end
    ActionCable.server.broadcast("game_channel_#{@game.id}", { game: @game.game_board, action: 'new_game' })
    render 'show'
  end

  def index; end

  private

  def get_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to new_game_path(id: @user.id), notice: 'User was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/games/_form.html.erb
<div id="game-board" data-game-id="<%= @game.id %>">
  <% 3.times do |i| %>
    <div class="row row-<%="#{i + 1}"%>">
      <% 3.times do |j| %>
        <% board_box =  @game.moves.find_by(position: i * 3 + j + 1) %>
        <% if board_box.present? %>
          <div class="col tile text-center" id="game-move-<%="#{board_box.position}"%>" style="cursor: pointer">
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/games/index.html.erb
<main class="container d-flex flex-column justify-content-center align-items-center">
  <h1 class="my-5"> <%= t('title') %> </h1>
  <form action=<%="#{ new_users_url}"%>
    <input type ="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="New Game" class="btn btn-danger">
  </form>
</main>

app/views/games/show.html.erb
<div class="d-flex justify-content-center">
  <div class="row">
    <div id="game-user" class="col m-lg-4" data-user-id="<%= @user.id %>">
      <span id="game_status"></span>
      <span data-user-connected="false"></span>
      <strong><%= @user.name.upcase %> </strong>
      <% if @game.new_game? %>
        <h3 class="justify-content-center" id="instructions"> Select box to get started! </h3>
      <% end %>
    </div>
      <%= render partial: "form", locals: { game: @game } %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tic Tac Toe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="justify-content-center card">
  <div class="card-header"><%= t('name') %></div>
  <div class="form-outline mb-4">
    <%= form_for @user do |form| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="row ">
      <div class="ps-3 col-lg-9">
        <%= form.text_field :name, class: "form-control", placeholder: t('username') %>
      </div>
      <div class="ps-3 col-lg-3 text-center">
        <%= form.submit t('start_game'), class: "btn btn-primary btn-block mb-2" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/create.html.erb
<div class="container">
  <br/>
  <div class="row justify-content-md-center">
    <div class="col-6 col-md-offset-3">
      <h1>
        <strong> Please input your name </strong>
      </h1>
      <%= render partial: "form" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container d-flex flex-column align-items-center">
  <br/>
  <%= link_to 'Home',root_path %>
  <div class="row ">
    <div class="col m-lg-4">
      <h1> <%= t('title') %> </h1>
    </div>
    <div class="row" >
      <div class="col">
        <%= render partial: "form" %>
      </div>
    </div>
  </div>
</div>